template = "https://github.com/giellalt/template-lang-und"
rev_id = 307
template_sha = "6f7d35fea20007282cb2085308400ab4050d8be7"

[replacements]
__GLOTTOLOG_ID__ = "komi1269"
__REPO__ = "lang-koi"
__UND2C__ = "koi"
__UNDEFINED__ = "Komi-Permyak"
__UND__ = "koi"
