template = "https://github.com/giellalt/template-lang-und"
rev_id = 289
template_sha = "599009dae90448ef6fe32b71f7a6880293f3d546"

[replacements]
__GLOTTOLOG_ID__ = "komi1269"
__REPO__ = "lang-koi"
__UND2C__ = "koi"
__UNDEFINED__ = "Komi-Permyak"
__UND__ = "koi"
