template = "https://github.com/giellalt/template-lang-und"
rev_id = 292
template_sha = "ae713c1306873a265055417badc511956629639d"

[replacements]
__GLOTTOLOG_ID__ = "komi1269"
__REPO__ = "lang-koi"
__UND2C__ = "koi"
__UNDEFINED__ = "Komi-Permyak"
__UND__ = "koi"
