[package]
name = "koi"
human_name = "Komi-Permyak"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.koi]
filename = "koi-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-koi"
platform = "windows"
uuid = "13770337-3C66-4383-8E0A-AF1F40E9C84F"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.koi"
package = "speller-koi"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-koi-mso"
platform = "windows"
uuid = "184C3A8C-4E53-4D12-8BE4-0CC548EC56A1"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-koi"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
